baseURL: "http://wirfuerunserekinder.org/"
title: Wir für unsere Kinder
paginate: 5
theme: hugo-PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

defaultContentLanguage: de

# googleAnalytics: UA-123-45

minify:
    disableXML: true
    # minifyOutput: true

languages:
    de:
        languageName: "Deutsch"
        weight: 2  
        menu:
            main:
                - name: Neues
                  url: news
                  weight: 1
                - name: Archiv
                  url: archives
                  weight: 5
                - name: Suche
                  url: search/
                  weight: 2
                - name: Index
                  url: tags/
                  weight: 4


outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    description: "Wir für unsere Kinder - wirfuerunserekinder.org"
    author: wirfuerunserekinder
    # author: ["Me", "You"] # multiple authors
    ### OWN PARAMS
    header_image_fil: "header_img.png"
    ### END OWN PARAMS
    defaultTheme: auto
    
    # disableThemeToggle: true
    ShowShareButtons: true
    ShowReadingTime: true
    # disableSpecial1stPost: true
    displayFullLangName: true
    # comments: false
    images: ["wirfuerunserekinder.jpg"]

    profileMode:
        enabled: true
        title: Wir Für Unsere Kinder
        subtitle: |  
            🧸 Unsere Kinder brauchen UNS 🧸 -
            starke Erwachsene, die sich schützend vor sie stellen. Wir Eltern und Familie stehen Seite an Seite und Hand in Hand zusammen. 
            Wir wollen für unsere Kinder: 
            🧡 ein unversehrtes Leben
            💙 ein Recht auf unbeschwertes  
                Aufwachsen in intakten 
                sozialen Strukturen 

            Unsere Kinder haben Recht auf:
            💛 Lebensfreude 
            ❤️ Empathie 
            💚 gesunde und freie Entwicklung 

            ❣️Unsere Kinder sind es wert,❣️
            dass wir sie mit all unserer Liebe und unserer Kraft beschützen. 

            Wir Menschen sind es wert, 
            dass wir frei sind, Rechte haben und selbstbestimmt leben. 

            🙋 Wir sind: 🙋
            Eltern, Großeltern und noch viele mehr. Wir haben uns gefunden und gehen gemeinsam als Familie durch diese Zeit.
            

        imageUrl: "wirfuerunserekinder.jpg"
        imageTitle: wirfuerunserekinder logo
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Inhalt
              url: topics
            - name: Neues
              url: news
            - name: Archiv
              url: archives
            - name: Index
              url: tags

    homeInfoParams:
        Title: "Wir für unsere Kinder"
        Content: >
            Willkommen bei der Initiative zur gegenseitigen Unterstützung bei neuen Herausforerungen die uns und unsere Kinder durch den chinesischen Schnupfen vor die Füße gelegt wurden ;-).
            
            wirfuerunserekinder ist eine freie Initiative die sich auf telegram organisert: [wirfuerunserekinder](https://t.me/WirFuerUnsereKinder).

    socialIcons:
        - name: github
          url: "https://github.com/adityatelange/hugo-PaperMod"
        - name: RsS
          url: "index.xml"

    label:
        text: "Home"
        icon: "favicon.ico"
        iconHeight: 32

    # analytics:
    #     google:
    #         SiteVerificationTag: "XYZabc"

    assets:
        favicon: "favicon.ico"
        favicon16x16: "favicon.ico"
        favicon32x32: "favicon.ico"
        apple_touch_icon: "favicon.ico"
        safari_pinned_tab: "favicon.ico"

    # cover:
    #     hidden: true # hide everywhere but not in structured data
    #     hiddenInList: true # hide on list pages and home
    #     hiddenInSingle: true # hide on single page

    # fuseOpts:
    #     isCaseSensitive: false
    #     shouldSort: true
    #     location: 0
    #     distance: 1000
    #     threshold: 0.4
    #     minMatchCharLength: 0
    #     keys: ["title", "permalink", "summary", "content"]

taxonomies:
    category: categories
    tag: tags
    series: series

# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         # noClasses: false
#         style: monokai

privacy:
    vimeo:
        disabled: false
        simple: true

    twitter:
        disabled: false
        enableDNT: true
        simple: true

    instagram:
        disabled: false
        simple: true

    youtube:
        disabled: false
        privacyEnhanced: true

services:
    instagram:
        disableInlineCSS: true
    twitter:
        disableInlineCSS: true
